"""empty message

Revision ID: 1b2c2bf089df
Revises: 1a428e838c8b
Create Date: 2026-03-31 15:17:40.808856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b2c2bf089df'
down_revision: Union[str, Sequence[str], None] = '1a428e838c8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lyrics',
    sa.Column('song_id', sa.String(length=36), nullable=False),
    sa.Column('lyrics', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('song_id')
    )
    op.create_index(op.f('ix_lyrics_song_id'), 'lyrics', ['song_id'], unique=True)
    op.create_table('song',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_song_id'), 'song', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_song_id'), table_name='song')
    op.drop_table('song')
    op.drop_index(op.f('ix_lyrics_song_id'), table_name='lyrics')
    op.drop_table('lyrics')
    # ### end Alembic commands ###
