"""empty message

Revision ID: 2a2567ebf14e
Revises: d5ba33e88118
Create Date: 2026-04-07 04:48:42.232621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a2567ebf14e'
down_revision: Union[str, Sequence[str], None] = 'd5ba33e88118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ppt-layout', sa.Column('background_color', sa.JSON(), nullable=False))
    op.add_column('ppt-shape', sa.Column('fill_color', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ppt-shape', 'fill_color')
    op.drop_column('ppt-layout', 'background_color')
    # ### end Alembic commands ###
