"""empty message

Revision ID: 383dc71b228a
Revises: ccbf2ec8bfb4
Create Date: 2026-05-05 08:00:47.191166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '383dc71b228a'
down_revision: Union[str, Sequence[str], None] = 'ccbf2ec8bfb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project-variable',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_project-variable_name'), 'project-variable', ['name'], unique=True)
    op.create_index(op.f('ix_project-variable_project_id'), 'project-variable', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project-variable_project_id'), table_name='project-variable')
    op.drop_index(op.f('ix_project-variable_name'), table_name='project-variable')
    op.drop_table('project-variable')
    # ### end Alembic commands ###
