"""empty message

Revision ID: 4cb3657336cc
Revises: 1b2c2bf089df
Create Date: 2026-04-04 22:50:18.774008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cb3657336cc'
down_revision: Union[str, Sequence[str], None] = '1b2c2bf089df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ppt-template',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('slide_size', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_ppt-template_user_id'), 'ppt-template', ['user_id'], unique=False)
    op.create_table('ppt-template-file',
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_index(op.f('ix_ppt-template-file_template_id'), 'ppt-template-file', ['template_id'], unique=True)
    op.create_index(op.f('ix_ppt-template-file_user_id'), 'ppt-template-file', ['user_id'], unique=False)
    op.create_table('ppt-layout',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['ppt-template.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_ppt-layout_template_id'), 'ppt-layout', ['template_id'], unique=False)
    op.create_table('ppt-shape',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('layout_id', sa.String(length=36), nullable=False),
    sa.Column('shape_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.JSON(), nullable=False),
    sa.Column('position', sa.JSON(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('placeholder', sa.Boolean(), nullable=False),
    sa.Column('type', sa.Enum('TEXT', 'IMAGE', 'SHAPE', 'TABLE', 'OTHER', name='shapetype'), nullable=False),
    sa.ForeignKeyConstraint(['layout_id'], ['ppt-layout.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('shape_id')
    )
    op.create_index(op.f('ix_ppt-shape_layout_id'), 'ppt-shape', ['layout_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ppt-shape_layout_id'), table_name='ppt-shape')
    op.drop_table('ppt-shape')
    op.drop_index(op.f('ix_ppt-layout_template_id'), table_name='ppt-layout')
    op.drop_table('ppt-layout')
    op.drop_index(op.f('ix_ppt-template-file_user_id'), table_name='ppt-template-file')
    op.drop_index(op.f('ix_ppt-template-file_template_id'), table_name='ppt-template-file')
    op.drop_table('ppt-template-file')
    op.drop_index(op.f('ix_ppt-template_user_id'), table_name='ppt-template')
    op.drop_table('ppt-template')
    # ### end Alembic commands ###
