"""empty message

Revision ID: 64c5bb76b4b8
Revises: d1633016ae3d
Create Date: 2026-05-03 23:26:21.627143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64c5bb76b4b8'
down_revision: Union[str, Sequence[str], None] = 'd1633016ae3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('user_id', sa.String(length=36), nullable=False))
    op.add_column('song', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('song', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_song_user_id'), 'song', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_song_user_id'), table_name='song')
    op.drop_column('song', 'updated_at')
    op.drop_column('song', 'created_at')
    op.drop_column('song', 'user_id')
    # ### end Alembic commands ###
