"""empty message

Revision ID: 734864f4a4e1
Revises: c61d1ad7aacc
Create Date: 2026-03-25 19:08:16.236146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '734864f4a4e1'
down_revision: Union[str, Sequence[str], None] = 'c61d1ad7aacc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credentials', 'access_key',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('credentials', 'refresh_key',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credentials', 'refresh_key',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('credentials', 'access_key',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    # ### end Alembic commands ###
