"""add cascade delete to layout and shape fk

Revision ID: b4d6c968abad
Revises: 12271b630378
Create Date: 2026-04-07 05:03:02.398301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4d6c968abad'
down_revision: Union[str, Sequence[str], None] = '12271b630378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ppt-layout_template_id_fkey'), 'ppt-layout', type_='foreignkey')
    op.create_foreign_key(None, 'ppt-layout', 'ppt-template', ['template_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('ppt-shape_layout_id_fkey'), 'ppt-shape', type_='foreignkey')
    op.create_foreign_key(None, 'ppt-shape', 'ppt-layout', ['layout_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ppt-shape', type_='foreignkey')
    op.create_foreign_key(op.f('ppt-shape_layout_id_fkey'), 'ppt-shape', 'ppt-layout', ['layout_id'], ['id'])
    op.drop_constraint(None, 'ppt-layout', type_='foreignkey')
    op.create_foreign_key(op.f('ppt-layout_template_id_fkey'), 'ppt-layout', 'ppt-template', ['template_id'], ['id'])
    # ### end Alembic commands ###
