"""empty message

Revision ID: c61d1ad7aacc
Revises: 0bf0d18ace5d
Create Date: 2026-03-25 18:53:40.530915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c61d1ad7aacc'
down_revision: Union[str, Sequence[str], None] = '0bf0d18ace5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('access_key', sa.String(length=512), nullable=False),
    sa.Column('refresh_key', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credentials_user_id'), 'credentials', ['user_id'], unique=True)
    op.create_table('principal',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('principal', sa.String(length=128), nullable=False),
    sa.Column('password_hashed', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_principal_principal'), 'principal', ['principal'], unique=True)
    op.create_index(op.f('ix_principal_user_id'), 'principal', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_principal_user_id'), table_name='principal')
    op.drop_index(op.f('ix_principal_principal'), table_name='principal')
    op.drop_table('principal')
    op.drop_index(op.f('ix_credentials_user_id'), table_name='credentials')
    op.drop_table('credentials')
    # ### end Alembic commands ###
