"""fix_shape_unique_constraint_to_composite

Revision ID: caa025761947
Revises: 4cb3657336cc
Create Date: 2026-04-04 23:00:07.261440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caa025761947'
down_revision: Union[str, Sequence[str], None] = '4cb3657336cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ppt-layout', ['id'])
    op.drop_constraint(op.f('ppt-shape_shape_id_key'), 'ppt-shape', type_='unique')
    op.create_unique_constraint('uq_ppt_shape_layout_shape', 'ppt-shape', ['layout_id', 'shape_id'])
    op.create_unique_constraint(None, 'ppt-shape', ['id'])
    op.create_unique_constraint(None, 'ppt-template', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ppt-template', type_='unique')
    op.drop_constraint(None, 'ppt-shape', type_='unique')
    op.drop_constraint('uq_ppt_shape_layout_shape', 'ppt-shape', type_='unique')
    op.create_unique_constraint(op.f('ppt-shape_shape_id_key'), 'ppt-shape', ['shape_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'ppt-layout', type_='unique')
    # ### end Alembic commands ###
