"""empty message

Revision ID: ccbf2ec8bfb4
Revises: 64c5bb76b4b8
Create Date: 2026-05-04 07:45:25.385090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccbf2ec8bfb4'
down_revision: Union[str, Sequence[str], None] = '64c5bb76b4b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ppt-shape', sa.Column('image', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ppt-shape', 'image')
    # ### end Alembic commands ###
