"""empty message

Revision ID: d1633016ae3d
Revises: e8f4a12c90ab
Create Date: 2026-04-29 12:34:40.343222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1633016ae3d'
down_revision: Union[str, Sequence[str], None] = 'e8f4a12c90ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'lyrics', 'song', ['song_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'project', ['id'])
    op.create_unique_constraint(None, 'project-container', ['id'])
    op.create_unique_constraint(None, 'project-part', ['id'])
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'project-part', type_='unique')
    op.drop_constraint(None, 'project-container', type_='unique')
    op.drop_constraint(None, 'project', type_='unique')
    op.drop_constraint(None, 'lyrics', type_='foreignkey')
    # ### end Alembic commands ###
