"""empty message

Revision ID: d5ba33e88118
Revises: caa025761947
Create Date: 2026-04-05 00:00:06.577277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5ba33e88118'
down_revision: Union[str, Sequence[str], None] = 'caa025761947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ppt-template', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('ppt-template', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('ppt-template-file', 'created_at')
    op.drop_column('ppt-template-file', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ppt-template-file', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('ppt-template-file', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('ppt-template', 'updated_at')
    op.drop_column('ppt-template', 'created_at')
    # ### end Alembic commands ###
